name: Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements_dev.txt
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        pylint --disable=locally-disabled --max-line-length 150 $(git ls-files '*.py')
    - name: Run pytest
      run: pytest
  coverage:
    needs: [ test ]
    name: coverage
    runs-on: ubuntu-latest
    steps:
    - uses: paambaati/codeclimate-action@v2.7.1
      env:
        CC_TEST_REPORTER_ID: eee088f724d03705460677092e8253d67eddddb7dd078848d049645c6c9405f1
      with:
        coverageCommand: coverage run -m pytest
        coverageLocations: |
          ${{github.workspace}}/coverage.lcov:lcov
        debug: true
